Recitation_Materials/Flask/model_example/messageboard_replies/profile/views/__init__.py
from profile.views import login
from profile.views import profile

Recitation_Materials/Flask/model_example/messageboard_replies/profile/views/login.py
from flask import Flask, request, abort, url_for, redirect, session, render_template, Blueprint, flash
from profile.model import User
from extensions import db

login_blueprint = Blueprint('login', __name__, template_folder = '../templates')

# by default, direct to login
@login_blueprint.route("/")
def default():
	return redirect("/login/")


@login_blueprint.route("/login/", methods = ["GET", "POST"])
def logger():
    #user logged in?
    if "username" in session:
        return redirect(url_for("profile.profile", username = session["username"]))
    # if not, and the incoming request is via POST try to log them in
    elif request.method == "POST":
        user = User.query.filter_by(username = request.form['user']).first()
        if user != None and user.password == request.form['pass']:
            session['username'] = user.username        
            return redirect(url_for("profile.profile", username=session["username"]))
    # otherwise, offer to log them in
    return render_template("profile/loginPage.html")

@login_blueprint.route("/logout/")
def unlogger():
	# if logged in, log out, otherwise offer to log in
	if "username" in session:
		# note, here were calling the .clear() method for the python dictionary builtin
		session.clear()
		return render_template("profile/logoutPage.html")
	else:
		return redirect(url_for("login.logger"))

"""
    Register New User
"""
@login_blueprint.route("/register/", methods = ["GET", "POST"])
def register():
	# if logged in, redirect to user page
	error = None
	if "username" in session:
		return redirect(url_for("profile.profile"))
	elif request.method == "POST":
	    user = User(request.form['user'], request.form['pass'], 
	                request.form['fname'], request.form['lname'])	    
	    response = db.session.add(user)
	    db.session.commit()
	    print(response)
	    return redirect(url_for("login.logger"))
	return render_template("profile/register.html")

Recitation_Materials/Flask/model_example/messageboard_replies/profile/views/profile.py
from flask import Flask, request, abort, url_for, redirect, session, Blueprint, render_template, jsonify
from profile.model import User, Blogpost
from extensions import db
import datetime


profile_blueprint = Blueprint('profile', __name__, template_folder = '../templates')
@profile_blueprint.route("/profile/", methods = ["GET", "POST"])
@profile_blueprint.route("/profile/<username>", methods = ["GET", "POST"])
def profile(username=None):
	if not username:
		if "username" in session:
			return redirect(url_for('profile.profile', username=session["username"]))
		else:
			return redirect(url_for("login.logger"))
	
	user = initialize_user(username)
	if "username" in session and session["username"] == username:
	    if request.method == "POST":
	        
	        if 'delete' in request.form:
	            delete_post()
	        elif 'title' in request.form:
	            post_to_feed(user)
	        elif 'reply' in request.form:
	            reply_post(user)
	        return redirect(url_for('profile.profile'))
	    posts = get_posts()
	    return render_template("profile/curProfile.html", username = username, posts = posts)
	    
	return render_template("profile/otherProfile.html", name=username, posts = posts)

def initialize_user(username):
    return User.query.filter_by(username = username).first()

def reply_post(user):
    if(request.form['body'] != ''):
        new_post = Blogpost(user.id,
                            request.form['body'],
                            datetime.datetime.now())
        new_post.set_parentId(int(request.form['id']))
        db.session.add(new_post)
        db.session.commit()

def delete_post():
    id = int(request.form['id'])
    Blogpost.query.filter_by(id = id).delete()
    db.session.commit()
	
def post_to_feed(user):
    if(request.form["title"] != '' and request.form['body'] != ''):
        new_post = Blogpost(user.id, 
                            request.form['body'], 
                            datetime.datetime.now(),
                            title = request.form['title'])
        db.session.add(new_post)
        db.session.commit()

def get_posts():
    raw_posts = Blogpost.query.all()
    posts = {}
    
    for post in raw_posts:
        posts[post.id] = {}
        posts[post.id]['content'] = post.serialize()
        if post.parentId ==-1:
            posts[post.id]['root'] = True
        else:
            posts[post.id]['root'] = False
        instances = Blogpost.query.filter_by(parentId = post.id).all()
        if(len(instances)>0):
            children = []
            for inst in instances:
                children.append(inst.id)
            posts[post.id]['children'] = children
    return posts
        

Recitation_Materials/Flask/model_example/messageboard_replies/templates/profile/curProfile.html
<!DOCTYPE html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<html>
	<head>
		<title>Your profile!</title>
		<style>
		    ul {
              list-style-type: none;
            }
		</style>
	</head>
	<body>
		Welcome back <strong>{{username}}</strong>!
		<a href="{{ url_for("login.unlogger") }}">click here to logout</a>
        <form action="" method="post">
            Title:  <input type="text" name="title" />
            <br />
            Body:  <input type="text" name="body" />
            <br />
            <input type="submit" name="submit" />
        </form>
        <ul>
            {% for post, value in posts.items() %}
                {% if value.root %}
                    {% with value = value, username = username, posts = posts %}
                    {% include "profile/post.html"%}
                    {% endwith %}
                {% endif %}

            {% endfor %}
        </ul>
    	<script>
        $(document).ready(function(){
            $("a").click(function(){
                $(this).hide();
                $($(this).attr("href")).show();
            });
        });
        </script>
	</body>

</html>

Recitation_Materials/Flask/model_example/messageboard_replies/templates/profile/loginPage.html
<!DOCTYPE html>
<html>
	<head>
		<title>Basic form</title>
	</head>
	<body>
		<form action="" method="post">
			Username:  <input type="text" name="user" />
			<br />
			Password:  <input type="text" name="pass" />
			<br />
			<input type="submit" value="submit" />
		</form>
		<a href="{{ url_for("login.register") }}">Create a new account.</a>
	</body>
</html>

Recitation_Materials/Flask/model_example/messageboard_replies/templates/profile/logoutPage.html
<!DOCTYPE html>
<html>
	<head>
		<title>Logged out</title>
	</head>
	<body>
		You have successfully been logged out!
	</body>
</html>

Recitation_Materials/Flask/model_example/messageboard_replies/templates/profile/otherProfile.html
<!DOCTYPE html>
<html>
	<head>
		<title>{{ name }}'s profile!</title>
	</head>
	<body>
		This is {{ name }}'s profile page.
	</body>
</html>

Recitation_Materials/Flask/model_example/messageboard_replies/templates/profile/post.html
<li>
{% if value.root %}
<div style = "border:1px solid black">
{%else%}
<div style = "bottom-border : 1px solid grey">
{%endif%}
<table style = "border-bottom: 1px solid grey">
<tr>
    <td><strong>{{value.content.fname}}</strong>({{value.content.username}}):</td>
    <td><strong>{{value.content.title}}</strong></td>
    <td>({{value.content.date}})</td>

    {% if value.content.username == username %}
    <td>
        <form action="" method="post">
            <input type="text" name = "id" value="{{value.content.id}}" style="display:none"/>
            <input type="submit" name="delete" value = "Delete" >
            </input>
        </form>
    </td>
    {% endif %}
</tr>

<tr>
    <td colspan = "2">{{value.content.text}}</td>
</tr>

<tr>
    <td colspan = "3"><a href = '#{{value.content.id}}' data-target = "#">Reply</a>
        <form id = "{{value.content.id}}" action="" method="post" style="display:none">
                <input type="text" name = "id" value="{{value.content.id}}" style="display:none"/>
                <input type="text" name="body" />
                <input type="submit" name="reply" value = "Submit" ></input>
        </form>
    </td>
</tr>
</table>
<ul>
    {% for id, next_value in posts.items() %}
        {% if id in value.children %}
            {% with value = next_value, username = username, posts = posts %}
            {% include "profile/post.html"%}
            {% endwith %}
        {% endif %}

    {% endfor %}
<ul>
</div>
</li>

Recitation_Materials/Flask/model_example/messageboard_replies/templates/profile/register.html
<!DOCTYPE html>
<html>
	<head>
		<title>Registration</title>
	</head>
	<body>
		<form action="" method="post">
			Username:  <input type="text" name="user" />
			<br />
			Password:  <input type="text" name="pass" />
			<br />
			First Name:  <input type="text" name="fname" />
			<br />
			Last Name:  <input type="text" name="lname" />
			<br />
			<input type="submit" value="submit" />
		</form>
	</body>
</html>